apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyhton-app
  labels:
    app: pyhton-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyhton-app
  template:
    metadata:
      labels:
        app: pyhton-app
    spec:
      containers:
      - name: pyhton-app
        image: harshil403/my-repo:latest
        ports:
        - containerPort: 8000
---

apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  selector:
    app: pyhton-app
  ports:
    - name: http
      port: 8081          # Service port
      targetPort: 8000  # Container port
  type: ClusterIP
